
CREATE TABLE fav_items (
    
 id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    youtube_id TEXT NOT NULL, 
    thumbnail TEXT NOT NULL,
    updated_ts TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_ts TIMESTAMPTZ NOT NULL DEFAULT now(),
    
);




