CREATE TYPE star_rating AS ENUM ('1', '2', '3', '4', '5');

CREATE TABLE ratings (
    
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    value star_rating NOT NULL,
    fav_items_id INTEGER REFERENCES fav_items(id) ON DELETE CASCADE,
  
    
);


